import Nav from "../../molecules/Nav";

const Terms = () => {
  return (
    <>
      <div className="flex justify-center items-center flex-col gap-[2rem] mt-20 text-white justify-center items-center w-full">
        <div className="w-[75%]">
                 <h1 className="text-center mb-10">THE NESTAGE.IO WEBSITE</h1>
        <p className="text-center mb-10">
          THE NESTAGE.IO WEBSITE IS ONLY AN INTER-FACE FOR INTERACTING WITH
          SMART CONTRACTS ON THE BLOCKCHAIN, AND YOU AGREE THAT YOU USE THE
          NESTAGE.IO WEBSITE(S) AT YOUR OWN RISK AND THAT THE SERVICES ARE
          PROVIDED 'AS IS AND 'AS AVAILABLE WITHOUT WARRANTY OF ANY KIND, EITHER
          EXPRESS OR IMPLIED, NOT EXPRESSLY STATED IN THE OFFICIAL
          DOCUMENTATION.
        </p>

        <p className="text-center mb-10">
          NO ADVICE OR INFORMATION, ORAL OR WRITTEN, OBTAINED BY YOU FROM
          PARTICIPANTS OF THE NESTAGE COMMUNITY CREATES ANY WARRANTY THAT IS NOT
          EXPRESSLY STATED IN THE OFFICIAL DOCUMENTATION
        </p>

        <p className="text-center mb-10">
          UNDER NO CIRCUMSTANCES WILL NESTAGE.IO BE LIABLE TO YOU OR ANY THIRD
          PARTY FOR ANY DAMAGES, INCLUDING BUT NOT LIMITED TO INDIRECT, SPECIAL,
          INCIDENTAL OR CONSEQUENTIAL DAMAGES OR OTHER DAMAGES INCLUDING DAMAGES
          FROM LOSS OF BUSINESS, LOST PROFITS, LOST SAVINGS, BUSINESS
          INTERRUPTION OR THE LIKES, ARISING FROM THE USE OF THE WEBSITE(S),
          CUSTOMER PRODUCTS OR EXTERNAL LINKS AND PARTNER WEBSITES
        </p>

        <p className="text-center mb-10">
          THE PLATFORM MAY CHARGE FEES FOR CERTAIN SERVICES, INCLUDING STAKING
          AND PARTICIPATION IN THE DECENTRALIZED MATRIX. ALL FEES WILL BE
          CLEARLY DISCLOSED BEFORE YOU ENGAGE IN ANY ACTIVITY THAT INCURS A FEE.
          USERS ARE RESPONSIBLE FOR ANY TRANSACTION FEES(GAS FEES) INCURRED ON
          THE BLOCKCHAIN NETWORK
        </p>
        <p className="text-center mb-10">
          BY PARTICIPATING IN THE DeFi STAKING, YOU AGREE TO LOCK YOUR
          CRYPTOCURRENCY ASSETS IN THE STAKING SMART CONTRACT FOR A SPECIFIED
          PERIOD, STAKING REWARDS ARE DISTRIBUTED ACCORDING TO THE TERMS
          SPECIFIED IN THE STAKING SMART CONTRACT. THE RATE OF REWARDS MAY VARY
          BASED ON NETWORK CONDITIONS AND OTHER FACTORS. YOU ACKNOWLEDGE THAT
          STAKING INVOLVES RISKS, INCLUDING POTENTIAL LOSS OF ASSETS DUE TO
          MARKET VOLATILITY, SMART CONTRACT VULNERABILITIES, OR OTHER UNFORESEEN
          EVENTS
        </p>

        <p className="text-center mb-10">
          YOU, YOUR AFFILIATES AND ANY THIRD PARTIES AGREE TO INDEMNIFY AND HOLD
          HARMLESS THE NESTAGE COMMUNITY FROM ANY AND ALL DAMAGES CLAIMED AS A
          RESULT OF THE USE OF SERVICES, PRODUCTS, INFORMATION AND RESOURCES
          OBTAINED FROM NESTAGE AND/OR IN ANY WAY, INCLUDING BUT NOT LIMITED TO,
          SPAM, ACCOUNT HIJACKING, IDENTITY THEFT, VIRUS ATTACK, FRAUDULENT OR
          CRIMINAL ACTIVITY (INCLUDING REAL, SUSPECTED, PROBABLE OR SUSPECTED
          FRAUD/CRIME.
        </p>
        <p className="text-center mb-10">
          NESTAGE SHALL NOT BE LIABLE UNDER ANY THEORY OF LIABILITY, INCLUDING
          BREACH OF CONTRACT, BREACH OF WARRANTY, INCLUDING NEGLIGENCE, PRODUCT
          LIABILITY OR OTHERWISE, EVEN IF PARTICIPANTS OF THE NESTAGE COMMUNITY
          OR ITS REPRESENTATIVES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH
          DAMAGES, AND EVEN IF THE REMEDY INDICATED BY NESTAGE FAILED TO ACHIEVE
          ITS PRIMARY PURPOSE. THE COMPANY'S PROGRAMS HAVE OPTIONS SUCH AS
          CANCELLATION OF AUTO-INVESTMENT AND/OR AUTO-UPGRADE
        </p>

        <p className="text-center mb-10">
          YOU AGREE THAT YOU ARE FULLY RESPONSIBLE FOR THE USE OF THE SERVICES
          AND ANY ACTIONS PERFORMED BY OTHER USERS. YOU ARE OBLIGED TO ENSURE
          THAT ALL OTHER USERS FOLLOW THE PROVISIONS OF THESE T&C. YOU ARE FULLY
          RESPONSIBLE FOR MAINTAINING THE SECURITY AND CONFIDENTIALITY OF YOUR
          ACCOUNTS, ESPECIALLY ACCESS DATA TO THEM.
        </p>

        <p className="text-center mb-10">
          THE USER WILL RECEIVE NOT 100%, BUT 85% OF THE REFERRAL BONUS. AT THE
          SAME TIME, 15% GOES TO THE PRODUCT FUND, WHICH HELPS TO COVER THE
          COSTS OF OUR DEVELOPMENT
        </p>
        <p className="text-center mb-10">
          NESTAGE.IO RESERVES THE RIGHT TO MODIFY THESE TERMS AT ANY TIME. ANY
          CHANGES WILL BE EFFECTIVE IMMEDIATELY UPON POSTING ON THE PLATFORM.
          YOUR CONTINUED USE OF THE PLATFORM AFTER THE POSTING OF REVISED TERMS
          CONSTITUTES YOUR ACCEPTANCE OF THE CHANGES
        </p>

        <p className="text-center mb-10">
          THESES TERMS CONSTITUTE THE ENTIRE AGREEMENT BETWEEN YOU AND
          NESTAGE.IO REGARDING YOUR USE OF THE PLATFORM AND SUPERSEDES ALL PRIOR
          AGREEMENT AND UNDERSTANDINGS, WHETHER WRITTEN OR ORAL
        </p>

        <p className="text-center mb-10">
          BY USING THE NESTAGE PLATFORM, YOU ACKNOWLEDGE THAT YOU HAVE READ,
          UNDERSTOOD AND AGREE TO BE BOUND BY THESE TERMS AND CONDITION
        </p>
          </div>
      </div>
    </>
  );
};

export default Terms;
